spring:
  datasource:
    #url: jdbc:sap://0cf459a8-b0ea-4026-a032-a38de030db86.hana.trial-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&traceFile=stdout&traceOptions=CONNECTIONS,API,STATISTICS,CLEANERS,TIMESTAMPS,ELAPSEDTIMES
   # username: DBADMIN
  #  password: Passw0rd!
    driver-class-name: com.sap.db.jdbc.Driver
  #  url: jdbc:sap://0cf459a8-b0ea-4026-a032-a38de030db86.hana.trial-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=DBADMIN
    url: jdbc:sap://0cf459a8-b0ea-4026-a032-a38de030db86.hana.trial-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=USR_CZG3AH1639MWT0OJQGRK099FM
    username: USR_CZG3AH1639MWT0OJQGRK099FM
    password: Rj8xi4MTY1YOlUj2J5a.YJNwmQgLVOyc89vn8Jzvgpc08WvW5QTYKS.cMska-Z1bbLigkZEuUENAjQiU3I1Lt.7QSidP2R0hA-Rg.u8xAYzH7OYsE2EX-k.ZBvKxaE0z
  jpa:
    database-platform: org.hibernate.dialect.HANAColumnStoreDialect
    hibernate:
      ddl-auto: create